# Generated by Django 4.1.7 on 2023-03-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('be', 'beginner'), ('ad', 'advanced'), ('ex', 'expert')], default='be', max_length=2, verbose_name='status'),
        ),
    ]
