# Generated by Django 4.1.7 on 2023-03-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0003_alter_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('be', 'beginner'), ('ad', 'advanced'), ('ex', 'expert')], default=('be', 'beginner'), max_length=2, verbose_name='status'),
        ),
    ]
