# Generated by Django 4.1.7 on 2023-03-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0004_alter_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spent_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='spent balance'),
        ),
    ]
